In [1]:
import numpy as np

A = np.array([ [1, 2, 3], [4, 5, 6] ])  # 2X3 행렬
B = np.array([ [-1, -2], [-3, -4], [-5, -6] ])  # 3X2 행렬

# (2X3) dot porduct (3X2) == (2X2) 행렬
C = np.dot(A, B)  # 행렬 곱 수행

# matrix A, B 형상 출력 => shape
print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print("C.shape ==", C.shape)
print(C)

A.shape == (2, 3) , B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


In [2]:
# scalar broadcast

A = np.array([ [1, 2], [3, 4] ]) 
b = 5

print(A+b)

[[6 7]
 [8 9]]


In [3]:
# matrix broadcast

C = np.array([ [1, 2], [3, 4] ]) 
D = np.array([4, 5])

print(C+D) 

[[5 7]
 [7 9]]


In [4]:
# 전치행렬

A = np.array([ [1, 2], [3, 4], [5, 6] ])  # 3X2행렬

B = A.T    # A의 전치행렬, 2X3 행렬

print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print(A)
print(B) 

A.shape == (3, 2) , B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [5]:
# vector 전치행렬

C = np.array([1, 2, 3, 4, 5])  # vector, matrix 아님
D = C.T      # C 는 vector 이므로 transpose 않됨

E = C.reshape(1, 5)    #  1X5 matrix
F = E.T    # E 의 전치행렬

print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print("E.shape ==", E.shape, ". F.shape ==", F.shape)
print(F)  

C.shape == (5,) , D.shape == (5,)
E.shape == (1, 5) . F.shape == (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [6]:
# reshape

A = np.array([10, 20, 30, 40, 50, 60]).reshape(3, 2)

print("A.shape ==", A.shape)
print(A)

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]


In [7]:
# indexing / slicing

print("A[0, 0] ==", A[0, 0], ", A[0][0] ==", A[0][0])
print("A[2, 1] ==", A[2, 1], ", A[2][1] ==", A[2][1]) 

print("A[0:-1, 1:2] ==", A[0:-1, 1:2]) 

print("A[ :, 0] ==", A[:, 0]) 
print("A[ :, :] ==", A[:, :]) 

A[0, 0] == 10 , A[0][0] == 10
A[2, 1] == 60 , A[2][1] == 60
A[0:-1, 1:2] == [[20]
 [40]]
A[ :, 0] == [10 30 50]
A[ :, :] == [[10 20]
 [30 40]
 [50 60]]


In [8]:
# iterator 예제

A = np.array([ [10, 20, 30, 40], [50, 60, 70, 80] ]) 

print(A, "\n") 
print("A.shape ==", A.shape, "\n") 

# 행렬 A 의 itrator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite']) 

while not it.finished:
    
    idx = it.multi_index
    
    print("current value => ", A[idx]) 
    
    it.iternext()

[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 

current value =>  10
current value =>  20
current value =>  30
current value =>  40
current value =>  50
current value =>  60
current value =>  70
current value =>  80
