In [1]:
import numpy as np

# 수치미분 함수

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

# sigmoid 함수

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [2]:
class LogicGate:
        
    def __init__(self, gate_name, xdata, tdata):
        
        self.name = gate_name
        
        # 입력 데이터, 정답 데이터 초기화
        self.__xdata = xdata.reshape(4,2)  # 4개의 입력데이터 x1, x2 에 대하여 batch 처리 행렬
        self.__tdata = tdata.reshape(4,1)  # 4개의 입력데이터 x1, x2 에 대한 각각의 계산 값 행렬
        
        # 2층 hidden layer unit : 6개 가정,  가중치 W2, 바이어스 b2 초기화
        self.__W2 = np.random.rand(2,6)  # weight, 2 X 6 matrix
        self.__b2 = np.random.rand(6)
        
        # 3층 output layer unit : 1 개 , 가중치 W3, 바이어스 b3 초기화
        self.__W3 = np.random.rand(6,1)
        self.__b3 = np.random.rand(1)
                        
        # 학습률 learning rate 초기화
        self.__learning_rate = 1e-2
    
        print(self.name + " object is created")
            
    def feed_forward(self):        # feed forward 를 통하여 손실함수(cross-entropy) 값 계산
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2  # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )    
    
    def loss_val(self):          # 외부 출력을 위한 손실함수(cross-entropy) 값 계산 
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2  # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )
    
    
    # 수치미분을 이용하여 손실함수가 최소가 될때 까지 학습하는 함수
    def train(self):
        
        f = lambda x : self.feed_forward()
        
        print("Initial loss value = ", self.loss_val())
        
        for step in  range(10001):
            
            self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
    
            self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
        
            self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
    
            self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)
    
            if (step % 400 == 0):
                print("step = ", step, "  , loss value = ", self.loss_val())
                
    
    # query, 즉 미래 값 예측 함수
    def predict(self, xdata):
        
        z2 = np.dot(xdata, self.__W2) + self.__b2         # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        if y > 0.5:
            result = 1  # True
        else:
            result = 0  # False
    
        return y, result

In [3]:
# AND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 0, 0, 1])

and_obj = LogicGate("AND", xdata, tdata)

and_obj.train()

AND object is created
Initial loss value =  5.840535083615841
step =  0   , loss value =  5.609765588483416
step =  400   , loss value =  2.1798903442341677
step =  800   , loss value =  2.0414073565518867
step =  1200   , loss value =  1.8038596110891651
step =  1600   , loss value =  1.4594878833873433
step =  2000   , loss value =  1.1051360149810563
step =  2400   , loss value =  0.8191922068974415
step =  2800   , loss value =  0.6087451807882351
step =  3200   , loss value =  0.4597443838168551
step =  3600   , loss value =  0.355547517191774
step =  4000   , loss value =  0.2821274816300895
step =  4400   , loss value =  0.22939701486032674
step =  4800   , loss value =  0.19061975646466078
step =  5200   , loss value =  0.16140541149859416
step =  5600   , loss value =  0.13888741685510447
step =  6000   , loss value =  0.12116685079709516
step =  6400   , loss value =  0.10696061539071057
step =  6800   , loss value =  0.09538290302835775
step =  7200   , loss value =  0.08580

In [4]:
# AND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(and_obj.predict(data))

(array([0.00016536]), 0)
(array([0.01178067]), 0)
(array([0.01262846]), 0)
(array([0.97646224]), 1)


In [5]:
# OR Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 1])

or_obj = LogicGate("OR", xdata, tdata)

or_obj.train()

OR object is created
Initial loss value =  2.212689045234357
step =  0   , loss value =  2.205296614482455
step =  400   , loss value =  1.850717689070251
step =  800   , loss value =  1.5625889130500852
step =  1200   , loss value =  1.2050453333027324
step =  1600   , loss value =  0.8687662489159175
step =  2000   , loss value =  0.6133910439311466
step =  2400   , loss value =  0.4406193227780353
step =  2800   , loss value =  0.32749945295615634
step =  3200   , loss value =  0.2524174189546395
step =  3600   , loss value =  0.2009843512760078
step =  4000   , loss value =  0.16449106306587105
step =  4400   , loss value =  0.13772631930228027
step =  4800   , loss value =  0.1175112541530571
step =  5200   , loss value =  0.10184861915309637
step =  5600   , loss value =  0.08944330575807852
step =  6000   , loss value =  0.07942961190851269
step =  6400   , loss value =  0.07121244149688043
step =  6800   , loss value =  0.06437222163993897
step =  7200   , loss value =  0.05860

In [6]:
# OR Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(or_obj.predict(data))

(array([0.02001798]), 0)
(array([0.99232183]), 1)
(array([0.99326034]), 1)
(array([0.9997005]), 1)


In [7]:
# NAND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([1, 1, 1, 0])

nand_obj = LogicGate("NAND", xdata, tdata)

nand_obj.train()

NAND object is created
Initial loss value =  3.4170137330312635
step =  0   , loss value =  3.381093254650571
step =  400   , loss value =  2.2386783059972633
step =  800   , loss value =  2.1139924601907
step =  1200   , loss value =  1.9075415363518984
step =  1600   , loss value =  1.5688825378040516
step =  2000   , loss value =  1.2105932613685404
step =  2400   , loss value =  0.907113365111014
step =  2800   , loss value =  0.6699365259160734
step =  3200   , loss value =  0.4983401738158731
step =  3600   , loss value =  0.37874383964013475
step =  4000   , loss value =  0.29566804193504925
step =  4400   , loss value =  0.23705341732544227
step =  4800   , loss value =  0.19470802798004483
step =  5200   , loss value =  0.16332229548883437
step =  5600   , loss value =  0.13947740846939255
step =  6000   , loss value =  0.12094605452592225
step =  6400   , loss value =  0.10624859200671379
step =  6800   , loss value =  0.09438000388711615
step =  7200   , loss value =  0.0846

In [8]:
# NAND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(nand_obj.predict(data))

(array([0.99979674]), 1)
(array([0.98785916]), 1)
(array([0.98800973]), 1)
(array([0.02266976]), 0)


In [9]:
# XOR Gate 객체 생성

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 0])


xor_obj = LogicGate("XOR", xdata, tdata)

xor_obj.train()

XOR object is created
Initial loss value =  4.735661084753321
step =  0   , loss value =  4.634876112146108
step =  400   , loss value =  2.775446295400008
step =  800   , loss value =  2.773263452948909
step =  1200   , loss value =  2.770917880220277
step =  1600   , loss value =  2.768128698254033
step =  2000   , loss value =  2.7645063286566858
step =  2400   , loss value =  2.7594693342625365
step =  2800   , loss value =  2.7521284652590445
step =  3200   , loss value =  2.741147600024205
step =  3600   , loss value =  2.7246269916546204
step =  4000   , loss value =  2.7000762411013386
step =  4400   , loss value =  2.6644912889238883
step =  4800   , loss value =  2.6145288972361405
step =  5200   , loss value =  2.5470986640337303
step =  5600   , loss value =  2.460951291588692
step =  6000   , loss value =  2.358547548152943
step =  6400   , loss value =  2.2456247222985573
step =  6800   , loss value =  2.127871832523778
step =  7200   , loss value =  2.007800434630348
ste

In [10]:
test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(xor_obj.predict(data))

(array([0.0833791]), 0)
(array([0.81125073]), 1)
(array([0.7467601]), 1)
(array([0.32748571]), 0)
