입력데이터 batch_size=1 인경우,  
outputs 는 각각의 batch data 에 대해서 출력됨. 즉 batch_size=1 이므로 전체출력 outputs 는 batch_size * hidden_size = 3 개의 원소를 가지는 Tensor

In [3]:
import torch

input_data = torch.Tensor([ [ [1], [2], [3] ] ])


MyRNNModel = torch.nn.RNN(input_size=1, hidden_size=3,
                          batch_first=True)


outputs, last_hs = MyRNNModel(input_data)

print(outputs.shape, '\n\n', outputs, '\n')
print(last_hs.shape,'\n\n', last_hs)

torch.Size([1, 3, 3]) 

 tensor([[[ 0.8645, -0.7350, -0.0752],
         [ 0.9160, -0.6650, -0.2979],
         [ 0.9635, -0.7853, -0.0346]]], grad_fn=<TransposeBackward1>) 

torch.Size([1, 1, 3]) 

 tensor([[[ 0.9635, -0.7853, -0.0346]]], grad_fn=<StackBackward0>)


입력데이터 batch_size=2 인 경우,
outputs 는 각각의 batch data 에 대해서 출력됨. 즉 batch_size=2 이므로 전체출력 outputs 는 batch_size * hidden_size = 6 개의 원소를 가지는 Tensor

In [4]:
import torch

input_data = torch.Tensor([ [ [1], [2], [3] ],
                            [ [4], [5], [6] ] ])


MyRNNModel = torch.nn.RNN(input_size=1, hidden_size=3,
                          batch_first=True)


outputs, last_hs = MyRNNModel(input_data)

print(outputs.shape, '\n\n', outputs, '\n')
print(last_hs.shape,'\n\n', last_hs)

torch.Size([2, 3, 3]) 

 tensor([[[ 0.1583,  0.4169, -0.2608],
         [ 0.1343,  0.6532, -0.7049],
         [ 0.0183,  0.8508, -0.9096]],

        [[ 0.4063,  0.7686, -0.9146],
         [ 0.2487,  0.9336, -0.9870],
         [ 0.1856,  0.9632, -0.9949]]], grad_fn=<TransposeBackward1>) 

torch.Size([1, 2, 3]) 

 tensor([[[ 0.0183,  0.8508, -0.9096],
         [ 0.1856,  0.9632, -0.9949]]], grad_fn=<StackBackward0>)


입력데이터 batch_size=3 인 경우,
outputs 는 각각의 batch data 에 대해서 출력됨. 즉 batch_size=3 이므로 전체출력 outputs 는 batch_size * hidden_size = 9 개의 원소를 가지는 Tensor

In [5]:
import torch

input_data = torch.Tensor([ [ [1], [2], [3] ],
                            [ [4], [5], [6] ],
                            [ [7], [8], [9] ] ])


MyRNNModel = torch.nn.RNN(input_size=1, hidden_size=3,
                          batch_first=True)


outputs, last_hs = MyRNNModel(input_data)

print(outputs.shape, '\n\n', outputs, '\n')
print(last_hs.shape,'\n\n', last_hs)

torch.Size([3, 3, 3]) 

 tensor([[[ 0.1338, -0.5827,  0.3698],
         [ 0.7415, -0.7868,  0.6803],
         [ 0.9540, -0.9446,  0.8801]],

        [[ 0.9405, -0.9829,  0.8920],
         [ 0.9962, -0.9941,  0.9739],
         [ 0.9989, -0.9981,  0.9879]],

        [[ 0.9975, -0.9994,  0.9859],
         [ 0.9999, -0.9998,  0.9970],
         [ 1.0000, -0.9999,  0.9985]]], grad_fn=<TransposeBackward1>) 

torch.Size([1, 3, 3]) 

 tensor([[[ 0.9540, -0.9446,  0.8801],
         [ 0.9989, -0.9981,  0.9879],
         [ 1.0000, -0.9999,  0.9985]]], grad_fn=<StackBackward0>)
