# 데이터 정의

In [2]:
import numpy as np

loaded_data = np.loadtxt('/content/PyTorch_LEC06_TrainData.csv', delimiter=',')

x_train_np = loaded_data[ : , 0:-1]
y_train_np = loaded_data[ : , [-1]]

print(loaded_data.shape, x_train_np.shape, y_train_np.shape)

(15, 4) (15, 3) (15, 1)


In [6]:
import torch
from torch import nn

x_train = torch.Tensor(x_train_np).float()
y_train = torch.Tensor(y_train_np).float()

# 신경망 모델 구축

In [8]:
class MyLinearRegressionModel(nn.Module):

    def __init__(self, input_nodes):
        super().__init__()
        self.linear_stack = nn.Sequential(
            nn.Linear(input_nodes, 1)
        )

    def forward(self, data):
        prediction = self.linear_stack(data)

        return prediction

In [16]:
model = MyLinearRegressionModel(3)

loss_function = nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

In [17]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.4212, -0.4304,  0.2209]], requires_grad=True)
Parameter containing:
tensor([0.5509], requires_grad=True)


In [18]:
nums_epoch = 2000

for epoch in range(nums_epoch+1):

    prediction = model(x_train)
    loss = loss_function(prediction, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('epoch = ', epoch, ' current loss = ', loss.item())

epoch =  0  current loss =  16.068117141723633
epoch =  100  current loss =  0.1425536572933197
epoch =  200  current loss =  0.01061574462801218
epoch =  300  current loss =  0.00329231983050704
epoch =  400  current loss =  0.0011100881965830922
epoch =  500  current loss =  0.0003750534961000085
epoch =  600  current loss =  0.0001267164188902825
epoch =  700  current loss =  4.28147213824559e-05
epoch =  800  current loss =  1.4467190339928493e-05
epoch =  900  current loss =  4.888381681666942e-06
epoch =  1000  current loss =  1.6523590602446347e-06
epoch =  1100  current loss =  5.588072440332326e-07
epoch =  1200  current loss =  1.8894591846674302e-07
epoch =  1300  current loss =  6.393444351715516e-08
epoch =  1400  current loss =  2.177985791718129e-08
epoch =  1500  current loss =  7.3275687739737805e-09
epoch =  1600  current loss =  2.51187026734101e-09
epoch =  1700  current loss =  8.649647109670866e-10
epoch =  1800  current loss =  3.1647987008831535e-10
epoch =  190

In [19]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 2.0000, -3.0000,  2.0000]], requires_grad=True)
Parameter containing:
tensor([1.3759e-05], requires_grad=True)


# 테스트 데이터 예측

In [24]:
x_test = torch.Tensor([ [5, 5, 0], [2, 3, 1], [-1, 0, -1], [10, 5, 2] ])

label = [ 2*data[0] -3*data[1] + 2*data[2]  for data in x_test ]

pred = model(x_test)

print(pred)
print('=============================================')
print(label)

tensor([[-5.0000],
        [-3.0000],
        [-4.0000],
        [ 9.0000]], grad_fn=<AddmmBackward0>)
[tensor(-5.), tensor(-3.), tensor(-4.), tensor(9.)]
