# 데이터 정의

In [1]:
import torch

x_train = torch.Tensor([2, 4, 6, 8, 10,
                        12, 14, 16, 18, 20]).view(10,1)
y_train = torch.Tensor([0, 0, 0, 0, 0,
                        0, 1, 1, 1, 1]).view(10,1)

print(x_train.shape, y_train.shape)

torch.Size([10, 1]) torch.Size([10, 1])


# 신경망 모델 구축

In [2]:
from torch import nn

class MyDeepLearningModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.deeplearning_stack = nn.Sequential(
            nn.Linear(1, 8),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )

    def forward(self, data):
        prediction = self.deeplearning_stack(data)
        return prediction

In [3]:
deeplearning_model = MyDeepLearningModel()

for name, child in deeplearning_model.named_children():
    for param in child.parameters():
        print(name, param)

deeplearning_stack Parameter containing:
tensor([[ 0.8563],
        [ 0.2287],
        [-0.9602],
        [ 0.2007],
        [ 0.5503],
        [ 0.3265],
        [ 0.0729],
        [ 0.4172]], requires_grad=True)
deeplearning_stack Parameter containing:
tensor([-0.7311,  0.0009,  0.3659, -0.6176, -0.8870, -0.8870,  0.2865,  0.0695],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([[-0.0181, -0.2728, -0.2050,  0.1117, -0.0905, -0.1740,  0.1518, -0.0790]],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([0.1045], requires_grad=True)


# 손실함수 및 옵티마이저 설정

In [4]:
loss_function = nn.BCELoss()

optimizer = torch.optim.SGD(deeplearning_model.parameters(), lr=1e-1)

In [5]:
nums_epoch = 5000

for epoch in range(nums_epoch+1):

    outputs = deeplearning_model(x_train)

    loss = loss_function(outputs, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('epoch = ', epoch, ' current loss = ', loss.item())

epoch =  0  current loss =  0.7203410863876343
epoch =  100  current loss =  0.389792263507843
epoch =  200  current loss =  0.31200623512268066
epoch =  300  current loss =  0.2660113275051117
epoch =  400  current loss =  0.2348921298980713
epoch =  500  current loss =  0.21211834251880646
epoch =  600  current loss =  0.19456753134727478
epoch =  700  current loss =  0.1805354356765747
epoch =  800  current loss =  0.169002503156662
epoch =  900  current loss =  0.1593160182237625
epoch =  1000  current loss =  0.15103843808174133
epoch =  1100  current loss =  0.14386208355426788
epoch =  1200  current loss =  0.13756518065929413
epoch =  1300  current loss =  0.1319836527109146
epoch =  1400  current loss =  0.12699195742607117
epoch =  1500  current loss =  0.12249322235584259
epoch =  1600  current loss =  0.11841149628162384
epoch =  1700  current loss =  0.11468535661697388
epoch =  1800  current loss =  0.11126599460840225
epoch =  1900  current loss =  0.10811368376016617
ep

In [6]:
for name, child in deeplearning_model.named_children():
    for param in child.parameters():
        print(name, param)

deeplearning_stack Parameter containing:
tensor([[ 0.3803],
        [-0.0713],
        [-0.2323],
        [ 0.3622],
        [ 0.4540],
        [ 0.4379],
        [-0.1216],
        [-0.0653]], requires_grad=True)
deeplearning_stack Parameter containing:
tensor([-4.0688,  0.7629,  2.4858, -3.8749, -4.8577, -4.6858,  1.3006,  0.6988],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([[ 1.2644, -0.2371, -0.7725,  1.2041,  1.5095,  1.4561, -0.4041, -0.2171]],
       requires_grad=True)
deeplearning_stack Parameter containing:
tensor([-5.6648], requires_grad=True)


# test data 이용한 예측

In [7]:
deeplearning_model.eval()

test_data = torch.Tensor([0.5, 3.0, 3.5, 11.0, 13.0, 31.0]).view(6,1)

pred = deeplearning_model(test_data)

logical_value = (pred > 0.5).float()

print(pred)
print(logical_value)

tensor([[2.9347e-14],
        [1.5186e-11],
        [5.2994e-11],
        [7.2894e-03],
        [5.2127e-01],
        [1.0000e+00]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])
