In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.3.0


In [2]:
x_data = np.array([2, 4, 6, 8, 10,
                   12, 14, 16, 18, 20]).astype('float32')

t_data = np.array([0, 0, 0, 0, 0,
                   0, 1, 1, 1, 1]).astype('float32')

In [3]:
model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(8, input_shape=(1,), 
                                activation='sigmoid'))


model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [4]:
model.compile(tf.keras.optimizers.SGD(learning_rate=0.1),
              loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 16        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 9         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [5]:
hist = model.fit(x_data, t_data, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7578 - accuracy: 0.4000
Epoch 2/500
1/1 [==============================] - 0s 1ms/step - loss: 0.7342 - accuracy: 0.4000
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7162 - accuracy: 0.4000
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7026 - accuracy: 0.4000
Epoch 5/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6923 - accuracy: 0.4000
Epoch 6/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6845 - accuracy: 0.6000
Epoch 7/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6785 - accuracy: 0.7000
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6739 - accuracy: 0.8000
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6704 - accuracy: 0.6000
Epoch 10/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6675 - accuracy: 0.6000
Epoch 11/500
1/1 [===========

In [6]:
test_data = np.array([0.5, 3.0, 3.5, 
                      11.0, 13.0, 31.0])

sigmoid_value = model.predict(test_data)

logical_value = tf.cast(sigmoid_value > 0.5,
                      dtype=tf.float32)

for i in range(len(test_data)):
    print(test_data[i], 
          sigmoid_value[i], 
          logical_value.numpy()[i])

0.5 [0.04223922] [0.]
3.0 [0.05836764] [0.]
3.5 [0.06577787] [0.]
11.0 [0.39917535] [0.]
13.0 [0.5249193] [1.]
31.0 [0.8609705] [1.]


In [7]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 8) dtype=float32, numpy=
 array([[ 0.9090736 , -0.18241355, -1.0119302 ,  0.1490751 ,  0.54939204,
          0.13127813,  0.13950464, -0.1802529 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(8,) dtype=float32, numpy=
 array([ 0.0556334 ,  1.338934  , -0.11622923, -0.6382603 ,  0.01752405,
        -0.17451894, -0.4021825 ,  1.2973777 ], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(8, 1) dtype=float32, numpy=
 array([[-0.43934634],
        [-2.4066896 ],
        [ 0.6325082 ],
        [ 1.3539454 ],
        [-0.03330512],
        [ 0.5639338 ],
        [ 1.0730162 ],
        [-2.3513427 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-0.57455003], dtype=float32)>]