# Tensor 만들기

In [1]:
import torch
import numpy as np

In [2]:
list_data = [ [10, 20], [30, 40] ]

tensor1 = torch.Tensor(list_data)

print(tensor1)
print(f"tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}")
print(f"tensor dtype: {tensor1.dtype}, tensor device: {tensor1.device}")

tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [3]:
if torch.cuda.is_available():
    tensor1 = tensor1.to("cuda")

print(f"tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}")
print(f"tensor dtype: {tensor1.dtype}, tensor device: {tensor1.device}")

tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cuda:0


In [4]:
numpy_data = np.array(list_data)

tensor2 = torch.Tensor(numpy_data)

print(tensor2)
print(f"tensor type: {type(tensor2)}, tensor shape: {tensor2.shape}")
print(f"tensor dtype: {tensor2.dtype}, tensor device: {tensor2.device}")

tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [5]:
numpy_data = np.array(list_data)

tensor2_1 = torch.from_numpy(numpy_data)

print(tensor2_1)
print(f"tensor type: {type(tensor2_1)}, tensor shape: {tensor2_1.shape}")
print(f"tensor dtype: {tensor2_1.dtype}, tensor device: {tensor2_1.device}")

tensor2_2 = torch.from_numpy(numpy_data).float()
print('====================================')

print(tensor2_2)
print(f"tensor type: {type(tensor2_2)}, tensor shape: {tensor2_2.shape}")
print(f"tensor dtype: {tensor2_2.dtype}, tensor device: {tensor2_2.device}")

tensor([[10, 20],
        [30, 40]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.int64, tensor device: cpu
tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [6]:
tensor3 = torch.rand(2, 2)
print(tensor3)

tensor4 = torch.randn(2, 2)
print(tensor4)

tensor([[0.7929, 0.7416],
        [0.7202, 0.8677]])
tensor([[ 0.0359,  2.3576],
        [-0.6327,  1.7375]])


In [7]:
tensor5 = torch.randn(2, 2)
print(tensor5)

numpy_from_tensor = tensor5.numpy()
print(numpy_from_tensor)

tensor([[ 0.1302, -0.0783],
        [-0.1032, -0.9706]])
[[ 0.13024028 -0.07826642]
 [-0.10320276 -0.97058386]]


# Tensor 연산

In [8]:
tensor6 = torch.Tensor([[1, 2, 3], [4, 5, 6]])

tensor7 = torch.Tensor([[7, 8, 9], [10, 11, 12]])

print(tensor6[0])
print(tensor6[:, 1:])
print(tensor7[0:2, 0:-1])
print(tensor7[-1, -1])
print(tensor7[... , -2])

tensor([1., 2., 3.])
tensor([[2., 3.],
        [5., 6.]])
tensor([[ 7.,  8.],
        [10., 11.]])
tensor(12.)
tensor([ 8., 11.])


In [9]:
tensor8 = tensor6.mul(tensor7)  # tensor8 = tensor6 * tensor7

print(tensor8)

tensor([[ 7., 16., 27.],
        [40., 55., 72.]])


In [10]:
tensor9 = tensor6.matmul(tensor7)   # tensor6 @ tensor7

RuntimeError: ignored

In [11]:
tensor7.view(3, 2)

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [12]:
tensor9 = tensor6.matmul(tensor7.view(3, 2))  # tensor6 @ tensor7.view(3, 2)

print(tensor9)

tensor([[ 58.,  64.],
        [139., 154.]])


# Tensor 합치기(Concatenate)

In [13]:
tensor_cat = torch.cat([tensor6, tensor7])

print(tensor_cat)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
tensor_cat_dim0 = torch.cat([tensor6, tensor7], dim=0)

print(tensor_cat_dim0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
tensor_cat_dim1 = torch.cat([tensor6, tensor7], dim=1)

print(tensor_cat_dim1)

tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])
